config/routes.rb
Rails.application.routes.draw do
  
  resources :songs
  resources :artists
  resources :videos, only: [:index, :new, :create]


  root 'rock#roll'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :songs
    
    mount_uploader :image, ImageUploader
	
	validates :name, presence: true, uniqueness: true
end

app/models/song.rb
class Song < ApplicationRecord
	belongs_to :artist

	validates :name, presence: true, uniqueness: true
	validates :artist_id, presence: true
	validates :rating, presence: true
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @song = Song.new
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    Song.where(artist_id: @artist.id).destroy_all
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :image)
    end
end

app/controllers/rock_controller.rb
class RockController < ApplicationController
  def roll
    @songs = Song.order(rating: :desc).limit(5)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @artists = Artist.order(name: :desc)
  end

  # GET /songs/1/edit
  def edit
    @artists = Artist.order(name: :desc)
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.create(song_params)

    if request.referrer == "http://localhost:3000/artists/#{@song.artist_id}"
      redirect_to :back
    else

      respond_to do |format|
        if @song.save
          format.html { redirect_to @song, notice: 'Song was successfully created.' }
          format.json { render :show, status: :created, location: @song }
        else
          format.html { render :new }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :rating, :artist_id, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/rock_helper.rb
module RockHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<body class="bioRhyme">
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@artist) do |f| %>
      <% if @artist.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

          <ul>
          <% @artist.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: "Artist/Group Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <strong>Aritst/Group Image:</strong>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "Let's Jam!", class: "btn btn-success" %>
  </div>
<% end %>
  </div>
</div>
</body>

app/views/artists/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="well">
			<h1>Editing Artist</h1>

			<%= render 'form', artist: @artist %>

			<p class="edit-btn">
				<%= link_to "Cancel Edit", @artist, class: "btn btn-warning" %>
			</p>
		</div>
	</div>
</div>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>
<body class="bioRhyme">
<h1>Artists</h1>

<%= link_to new_artist_path do %>
  <i class="glyphicon glyphicon-plus add-icon"></i> Add
<% end %>

<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-md-6">
      <div class="well">
        <p>
          <% if !artist.image.nil? %>
            <%= image_tag artist.image.url, class: "artist-index-pic" %>
          <% end %>
        </p>
        <h3><%= link_to artist.name, artist %></h3>
        <p>
          <%= link_to edit_artist_path(artist) do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>&nbsp;
          <%= link_to artist, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>
</body>

app/views/artists/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="well">
			<h1>New Artist</h1>

			<%= render 'form', artist: @artist %>
		</div>
	</div>
</div>

app/views/artists/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="well artist-index-well">
			<h2>
			  <%= @artist.name %>
			</h2>

			<p>
				<%= image_tag @artist.image.url, class: "artist-show-pic" %>
			</p>

			<p>
				<% @artist.songs.each_with_index do |song, index| %>
					<% if index < (@artist.songs.length - 1) %>
						<%= link_to song.name, song %>, 
					<% else %>
						<%= link_to song.name, song %>
					<% end %>
				<% end %>
			</p>

			<p id="add_song_by_artist">
				<i class="glyphicon glyphicon-music"></i> Add New Song By Artist
			</p>

			<div class="invisible" id="song_by_artist_form">
				<%= render 'songs/form', song: @song %>
			</div>

			<p>
				<%= link_to edit_artist_path(@artist) do %>
					<i class="glyphicon glyphicon-pencil"></i>
				<% end %>&nbsp;
	      <%= link_to @artist, method: :delete, data: { confirm: 'Are you sure?' } do %>
	        <i class="glyphicon glyphicon-trash"></i>
	      <% end %>
	    </p>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head class="bioRhyme">
    <title>RockNRoll</title>
    <%= csrf_meta_tags %>
 
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="bioRhyme">

 <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"><%= image_tag "rock-logo.png" %>Kyle's Top Hits</h3>
              <nav>
                <ul class="nav masthead-nav">
                	<% if current_page?(root_path) %>
                  <li class="active">
                  	<% else %>
                  	<li>
                  		<% end %>
                  	<%= link_to 'Top 5',  root_path %>
                  </li>
                	<% if current_page?(artists_path) %>
                  <li class="active">
                  	<% else %>
                  	<li>
                  		<% end %>
                  	<%= link_to 'Artists',  artists_path %>
                  </li>
                	<% if current_page?(songs_path) %>
                  <li class="active">
                  	<% else %>
                  	<li>
                  		<% end %>
                  	<%= link_to 'Songs',  songs_path %>
                  </li>


                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
     			  <%= yield %>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p class="bioRhyme">Kyle's Rocking Productions, &copy; 2016</p>
            </div>
          </div>

        </div>

      </div>

    </div>

  
  </body>
</html>

app/views/rock/roll.html.erb
<body class="bioRhyme">
TOP 5 SONGS

<div class="row">
  <% @songs.each_with_index do |song, index| %>
    <% if index == 4 %>
      <div class="col-md-6 col-md-offset-3">
    <% else %>
      <div class="col-md-6">
    <% end %>
      <div class="well">
        <h3><%= link_to song.name, song %></h3>
        <p>by <%= link_to song.artist.name, song.artist %></p>
        <p>
          <% song.rating.times do %>
            <i class="glyphicon glyphicon-star yellow-star"></i>
          <% end %>
          <% (10 - song.rating).times do %>
            <i class="glyphicon glyphicon-star"></i>
          <% end %>
        </p>
        <p>
          <%= link_to edit_song_path(song) do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>&nbsp;
          <%= link_to song, method: :delete, data: { confirm: 'Are you Positive?' } do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

</body>

app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: "Song Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.select(:rating, %w(1 2 3 4 5 6 7 8 9 10), { include_blank: "Rating" }, class: "form-control") %>
  </div>

  <div class="form-group">
    <% if current_page?(new_song_path) || current_page?(edit_song_path) %>
      <%= f.select(:artist_id, @artists.collect { |a| [a.name, a.id] }, { include_blank: "Please Select an Artist" }, class: "form-control") %>
    <% else %>
      <%= f.hidden_field :artist_id, value: @artist.id %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.text_field :video, placeholder: "Link to Video (Use Embed 'src')", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Hit Play!", class: "btn btn-success" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="well">
			<h1>Editing Song</h1>

			<%= render 'form', song: @song %>

			<p class="edit-btn">
				<%= link_to 'Cancel Edit', @song, class: "btn btn-warning" %>
			</p>
		</div>
	</div>
</div>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>
<body class="bioRhyme">
<p id="notice"><%= notice %></p>

<h1>My Songs</h1>

<%= link_to new_song_path do %>
  <i class="glyphicon glyphicon-plus add-icon"></i> Add
<% end %>

<div class="row">
  <% @songs.each do |song| %>
    <div class="col-md-6">
      <div class="well">
        <h3><%= link_to song.name, song %></h3>
        <p>by <%= link_to song.artist.name, song.artist %></p>
        <p>
          <% song.rating.times do %>
            <i class="glyphicon glyphicon-star yellow-star"></i>
          <% end %>
          <% (10 - song.rating).times do %>
            <i class="glyphicon glyphicon-star"></i>
          <% end %>
        </p>
        <p>
          <%= link_to edit_song_path(song) do %>
            <i class="glyphicon glyphicon-pencil"></i>
          <% end %>&nbsp;
          <%= link_to song, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>

</body>

app/views/songs/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="well">
			<h1>New Song</h1>

			<%= render 'form', song: @song %>
		</div>
	</div>
</div>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>
<body class="bioRhyme">
<p class="bioRhyme">
<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="well">
			<h2>
			  <%= @song.name %>
			</h2>

			<p>
			  by <%= link_to @song.artist.name, @song.artist %>
			</p>

			<p>
			  <% @song.rating.times do %>
            <i class="glyphicon glyphicon-star yellow-star"></i>
          <% end %>
          <% (10 - @song.rating).times do %>
            <i class="glyphicon glyphicon-star"></i>
          <% end %>
			</p>

			<p>
				<%= link_to edit_song_path(@song) do %>
					<i class="glyphicon glyphicon-pencil"></i>
				<% end %>&nbsp;
        <%= link_to @song, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </p>

      <% if !@song.video.nil? %>
	      <div class="embed-responsive embed-responsive-16by9">
  	    	<iframe src="<%= @song.video %>" frameborder="0" allowfullscreen></iframe>
    	  </div>
    	<% end %>
    </div>
  </div>
</div>
</body>